export const allMuscles = [
    'Front_Calves', 'Front_Forearms', 'Front_Shoulders', 'Front_Traps',
    'Abdominals', 'Biceps', 'Chest', 'Quads',

    'Back_Calves', 'Back_Forearms', 'Back_Shoulders', 'Back_Traps',
    'Glutes', 'Hamstrings', 'Lats', 'Lower_Back', 'Traps_mid', 'Triceps'
]

export const mostMuscles = [
    "Front_Calves", "Front_Forearms", "Front_Shoulders", "Front_Traps", "Abdominals", "Biceps",
    "Chest", "Quads", "Glutes", "Hamstrings", "Lats", "Lower_Back", "Traps_mid", "Triceps"
]

export const allExercises = [
    'No exercise selected',
    'Ab Wheel Rollout',
    'Arnold Press',
    'Back Extension',
    'Behind The Back Barbell Shrug',
    'Behind The Back Cable Curl',
    'Behind The Neck Press',
    'Belt Squat',
    'Bench Dips',
    'Bench Pin Press',
    'Bench Press',
    'Bench Pull',
    'Bent Arm Barbell Pullover',
    'Bent Over Row',
    'Bicycle Crunch',
    'Box Squat',
    'Bulgarian Split Squat',
    'Cable Overhead Tricep Extension',
    'Cable Pull Through',
    'Calf Raise',
    'Cheat Curl',
    'Chest Dip',
    'Chest Press',
    'Chest Supported Dumbbell Row',
    'Chin Ups',
    'Clap Pull Up',
    'Clean',
    'Clean High Pull',
    'Clean Pull',
    'Clean and Jerk',
    'Clean and Press',
    'Close Grip Bench Press',
    'Close Grip Lat Pulldown',
    'Close Grip Push Up',
    'Concentration Curl',
    'Crossover',
    'Crunches',
    'Curl',
    'Deadlift',
    'Decline Bench Press',
    'Decline Crunch',
    'Decline Dumbbell Fly',
    'Decline Push Up',
    'Deficit Deadlift',
    'Diamond Push Ups',
    'Donkey Calf Raise',
    'Dumbbell High Pull',
    'Dumbbell Incline Y Raise',
    'Dumbbell Tricep Kickback',
    'Front Raise',
    'Glute Bridge',
    'Hack Squat',
    'Inverted Row',
    'Kickback',
    'Lunge',
    'Tricep Dip',
    'Woodchoppers',
]

export const musclesWorked = {
    'Ab Wheel Rollout': ['Abdominals'],
    'Arnold Press': ['Front_Shoulders', 'Back_Shoulders'],
    'Back Extension': ['Lower_Back'],
    'Behind The Back Barbell Shrug': ['Front_Shoulders', 'Back_Shoulders'],
    'Behind The Back Cable Curl': ['Biceps'],
    'Behind The Neck Press': ['Front_Shoulders', 'Back_Shoulders'],
    'Belt Squat': ['Glutes'],
    'Bench Dips': ['Triceps'],
    'Bench Pin Press': ['Chest'],
    'Bench Press': ['Chest'],
    'Bench Pull': ['Lats', 'Lower_Back', 'Traps_mid', 'Front_Traps', 'Back_Traps'],
    'Bent Arm Barbell Pullover': ['Lats'],
    'Bent Over Row': ['Lats', 'Lower_Back', 'Traps_mid', 'Front_Traps', 'Back_Traps'],
    'Bicycle Crunch': ['Abdominals'],
    'Box Squat': ['Glutes'],
    'Bulgarian Split Squat': ['Quads'],
    'Cable Overhead Tricep Extension': ['Triceps'],
    'Cable Pull Through': ['Abdominals'],
    'Calf Raise': ['Front_Calves', 'Back_Calves'],
    'Cheat Curl': ['Biceps'],
    'Chest Dip': ['Chest'],
    'Chest Press': ['Chest'],
    'Chest Supported Dumbbell Row': ['Lats', 'Lower_Back', 'Traps_mid', 'Front_Traps', 'Back_Traps'],
    'Chin Ups': ['Lats'],
    'Clap Pull Up': ['Lats'],
    'Clean': ['Glutes', 'Hamstrings', 'Front_Calves', 'Back_Calves', 'Front_Shoulders', 'Back_Shoulders'],
    'Clean High Pull': ['Glutes', 'Hamstrings', 'Front_Calves', 'Back_Calves', 'Front_Shoulders', 'Back_Shoulders'],
    'Clean Pull': ['Glutes', 'Hamstrings', 'Front_Calves', 'Back_Calves', 'Front_Shoulders', 'Back_Shoulders'],
    'Clean and Jerk': ['Glutes', 'Hamstrings', 'Front_Calves', 'Back_Calves', 'Front_Shoulders', 'Back_Shoulders'],
    'Clean and Press': ['Glutes', 'Hamstrings', 'Front_Calves', 'Back_Calves', 'Front_Shoulders', 'Back_Shoulders'],
    'Close Grip Bench Press': ['Triceps'],
    'Close Grip Lat Pulldown': ['Lats'],
    'Close Grip Push Up': ['Triceps'],
    'Concentration Curl': ['Biceps'],
    'Crossover': ['Chest'],
    'Crunches': ['Abdominals'],
    'Curl': ['Biceps'],
    'Deadlift': ['Lower_Back'],
    'Decline Bench Press': ['Chest'],
    'Decline Crunch': ['Abdominals'],
    'Decline Dumbbell Fly': ['Chest'],
    'Decline Push Up': ['Chest'],
    'Deficit Deadlift': ['Lower_Back'],
    'Diamond Push Ups': ['Triceps'],
    'Donkey Calf Raise': ['Front_Calves', 'Back_Calves'],
    'Dumbbell High Pull': ['Glutes', 'Hamstrings', 'Front_Calves', 'Back_Calves', 'Front_Shoulders', 'Back_Shoulders'],
    'Dumbbell Incline Y Raise': ['Front_Shoulders', 'Back_Shoulders'],
    'Dumbbell Tricep Kickback': ['Triceps'],
    'Front Raise': ['Front_Shoulders', 'Back_Shoulders'],
    'Glute Bridge': ['Glutes'],
    'Hack Squat': ['Quads'],
    'Inverted Row': ['Lats', 'Lower_Back', 'Traps_mid', 'Front_Traps', 'Back_Traps'],
    'Kickback': ['Triceps'],
    'Lunge': ['Quads'],
    'Tricep Dip': ['Triceps'],
    'Woodchoppers': ['Abdominals'],
    }